apiVersion: v1
kind: Service
metadata:
  labels:
    app: ci-app
  name: ci-app
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: resilient-wombat
spec:
  ports:
  - name: 443-8443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ci-app
  type: LoadBalancer
